### ISSUE TITLE
IDE Error for SpongeCommon

### ISSUE THREAD

**Issue by liach** [minecraft-dev/MinecraftDev#179]
This happens when I open SpongeCommon with the latest version of the plugin as of the submission of this issue.
```
C:\Users\chen\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_snapshot\20170210\1.11.2\srgs\mcp-srg.srg
java.nio.file.NoSuchFileException: C:\Users\chen\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_snapshot\20170210\1.11.2\srgs\mcp-srg.srg
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at java.nio.file.Files.readAllLines(Files.java:3202)
	at java.nio.file.Files.readAllLines(Files.java:3242)
	at com.demonwav.mcdev.platform.mcp.srg.McpSrgMap$Companion.parse(McpSrgMap.kt:58)
	at com.demonwav.mcdev.platform.mcp.srg.SrgManager$parse$$inlined$runAsync$1.run(promise.kt:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by liach** [comment]
More exactly: 2016.3-0.5.6

**Comment by DemonWav** [comment]
Latest version is `2016.3-0.5.8`. Though I'm not sure that would fix whatever issue that's causing this.

**Comment by liach** [comment]
Well, in my IDE I tried to update but didn't found a later version

**Comment by Minecrell** [comment]
Refreshing your Gradle project should fix the issue. The error can only happen if you delete files in the Gradle cache without re-importing the Gradle project.

**Comment by DemonWav** [comment]
> Well, in my IDE I tried to update but didn't find a later version

IntelliJ can be slow in checking for updates sometimes, especially when I push out several updates in quick succession.

**Comment by liach** [comment]
Might this relate to https://github.com/ModCoderPack/MCPBot-Issues/issues/360 as shown in log?

**Comment by liach** [comment]
Still happens as of 0.5.8 and after refreshing the gradle project and reopening it.

**Comment by liach** [comment]
![image](https://cloud.githubusercontent.com/assets/7806504/23833166/2c37a0f8-06ff-11e7-9c72-5ac05c3cf12f.png)

**Comment by Minecrell** [comment]
@liach Did you run `setupDecompWorkspace`?

**Comment by liach** [comment]
I ran it long long before. Should I run it again?

**Comment by Minecrell** [comment]
Yes, you need to run it again if you delete files in the Gradle cache.

**Comment by liach** [comment]
Looks good now. Well, I don't think I ever deleted those cache...

**Comment by Minecrell** [comment]
@liach Then it's the second thing. You need to run `setupDecompWorkspace` when you update your Sponge dev environment.

**Comment by liach** [comment]
Might it be caused by `gradle clean cleanCache`?

**Comment by Minecrell** [comment]
@liach Yes, `cleanCache` will delete the Gradle cache (at least the ForgeGradle part of it).
